baseURL = "http://billylkc.com"
languageCode = "en-us"
title = "Fullstack Data Science Blog"
description = "Fullstack Data Science Blog"
theme = "dream"
defaultContentLanguage = "en"
headerTitle = "Fullstack Data Science Blog"
googleAnalytics = "260697059"
paginate = 14

[params]
  background = "#fff"
  backgroundImage = "https://storage.googleapis.com/billylkc-blog-image/images/background_3.jpg"
  linkColor = "seagreen"
  gtm_id = "GTM-WVJS63K"

  # dark mode
  defaultDark = false
  backgroundDark = "black"
  # backgroundImageDark = "/me/background-dark.jpg"
  darkLinkColor = "darkseagreen"

  author = "Billy Lam"
  avatar = "https://storage.googleapis.com/billylkc-blog-image/images/avatar_gopher.jpg"
  description = "A blog to share about Algorithm, Programming, DevOps and Cloud. Come by and learn more about Python, Go and Data Science!"
  keywords = "Data Science, Python, Golang, Go, emacs, Visualization, Devops, Cloud, GCP, Algorithm, Modeling, Big Data, Deployment, Intelligence, R, Mining, Analytics, Data, Business, Predictive, Maintainability, Jenkins"
  image = "https://storage.googleapis.com/billylkc-blog-image/images/data.jpg"
  AuthorName = "Billy Lam"
  GitHubUser = "billylkc"
  Subtitle = "The dark side of Data Science"
  headerTitle = "Fullstack Data Science Blog"
  motto = "The dark side of Data Science"
  email = "billy.lamkc@gmail.com"
  twitter = "billylkc"
  linkedin = "billylkc"
  github = "billylkc"
  siteStartYear = 2021
  favicon = "img/favicon.png"

  highlightjs = false
  highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "gruvbox-light"
  highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true
  hasTwitterEmbed = false
  reversePostAndAside = true
  shareInAside = false
  fixedNav = false

[permalinks]
  posts = "/:2006/:01/:02/:slug/"

# in your config.toml
[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true