# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Dream"
license = "MIT"
licenselink = "https://github.com/g1eny0ung/hugo-theme-dream/blob/master/LICENSE"
description = "Another Data Science Blog"
homepage = "http://billylkc.com/"
tags = ["flip", "masonry layout", "i18n", "blog", "google-analytics", "disqus", "responsive", "copyright", "avatar", "motto", "social links", "creative", "personal", "light mode", "dark mode", "search"]
features = ["flip", "masonry layout", "i18n", "blog", "google-analytics", "disqus", "responsive", "copyright", "avatar", "motto", "social links", "creative", "personal", "light mode", "dark mode", "search"]
min_version = "0.57.2"

[author]
  name = "Billy Lam"
  homepage = "https://github.com/billylkc"


# If porting an existing theme
# [original]
#   name = "g1eny0ung's blog"
#   homepage = "https://g1eny0ung.github.io"
#   repo = "https://github.com/g1eny0ung/blog"
